# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m46XneXQdixk8rxxMMzzYvm002kWGjnb
"""

# import pandas as pd
# load google drive

# df1 = pd.read_csv('/content/drive/MyDrive/clrp/clrp_rev.csv')
# df2 = pd.read_csv('/content/drive/MyDrive/clrp/clrp_project.csv')

# revised to have compact years and added Anticipated Opening Year
import pandas as pd
import numpy as np
import re

# -------------------------------
# Load data
# -------------------------------
df1 = pd.read_csv('/content/drive/MyDrive/clrp/clrp_rev_cvta.csv')
df2 = pd.read_csv('/content/drive/MyDrive/clrp/clrp_project_chest.csv')

# -------------------------------
# 1. Clean df1: handle special dash characters
# -------------------------------
df1_clean = df1.copy()

def clean_numeric(val):
    if isinstance(val, str):
        val = re.sub(r'[ \s\-–—]+', '', val.strip())
        if val == '' or val == '-':
            return 0
        try:
            return float(val)
        except:
            return 0
    return val

for col in df1_clean.columns:
    if col != 'Years':
        df1_clean[col] = df1_clean[col].apply(clean_numeric)
        df1_clean[col] = pd.to_numeric(df1_clean[col], errors='coerce').fillna(0)

df1_clean = df1_clean.set_index('Years')
years = list(range(2033, 2051))
BASE_YEAR = 2033
ESCALATION_RATE = 0.03
CAP_PERCENTAGE = 0.9

def calculate_yoe_cost(base_cost, expenditure_year):
    n = expenditure_year - BASE_YEAR
    return base_cost * ((1 + ESCALATION_RATE) ** n)

def calculate_base_cost(yoe_cost, expenditure_year):
    n = expenditure_year - BASE_YEAR
    return yoe_cost / ((1 + ESCALATION_RATE) ** n)

print("=" * 80)
print("CLEANED DF1 - AVAILABLE FUNDING BY YEAR (100%)")
print("=" * 80)
print(df1_clean.head())
print(f"\nTotal years: {len(years)} (2033-2050)")
print("\n")

# -------------------------------
# 2. Prepare df2 projects
# -------------------------------
df2_work = df2.copy()
df2_work['B/C Rank'] = pd.to_numeric(df2_work['B/C Rank'], errors='coerce')
df2_work['Total Cost ($M)'] = pd.to_numeric(df2_work['Total Cost ($M)'], errors='coerce').fillna(0)
df2_work = df2_work.dropna(subset=['Primary Funding Source'])
df2_work = df2_work[df2_work['Total Cost ($M)'] > 0]
df2_work['Remaining Cost Base'] = df2_work['Total Cost ($M)'].copy()
df2_work['Fully Funded'] = False
df2_work['Comment'] = ""

# Initialize year columns for primary source allocations
for yr in years:
    if yr not in df2_work.columns:
        df2_work[yr] = 0.0
    else:
        df2_work[yr] = pd.to_numeric(df2_work[yr], errors='coerce').fillna(0)

# Initialize CVTA allocation columns
for yr in years:
    df2_work[f'cvta_{yr}'] = 0.0
df2_work['CVTA_Allocated_Base'] = 0.0
df2_work['CVTA_Allocated_YOE'] = 0.0

# Sort projects by B/C Rank (lower = higher priority)
df2_work['B/C Rank'] = df2_work['B/C Rank'].fillna(999)
df2_work = df2_work.sort_values('B/C Rank').reset_index(drop=True)

print(f"Total projects to allocate: {len(df2_work)}")
print(f"Funding sources in df2: {df2_work['Primary Funding Source'].unique()}")
print(f"Funding sources in df1: {list(df1_clean.columns)}")
print("\n")

# -------------------------------
# 3. STEP 1: Allocate CVTA only to Chesterfield projects (front-loaded)
# -------------------------------
chesterfield_mask = df2_work['County'] == 'Chesterfield'
chesterfield_indices = df2_work[chesterfield_mask].index

def allocate_funds_frontloaded(project_indices, source_budget_yoe, source_name, year_col_prefix=''):
    for idx in project_indices:
        remaining_base = df2_work.at[idx, 'Remaining Cost Base']
        if remaining_base <= 0:
            continue
        allocated_base = 0
        allocated_yoe = 0
        for yr in years:
            if remaining_base - allocated_base <= 1e-6:
                break
            annual_cap_yoe = source_budget_yoe.get(yr, 0)
            if annual_cap_yoe <= 0:
                continue
            proposed_base = remaining_base - allocated_base
            proposed_yoe = calculate_yoe_cost(proposed_base, yr)
            if proposed_yoe > annual_cap_yoe:
                max_base = calculate_base_cost(annual_cap_yoe, yr)
                proposed_base = max_base
                proposed_yoe = annual_cap_yoe
            if proposed_base <= 0:
                continue
            if year_col_prefix:
                df2_work.at[idx, f'{year_col_prefix}{yr}'] += proposed_yoe
            else:
                df2_work.at[idx, yr] += proposed_yoe
            allocated_base += proposed_base
            allocated_yoe += proposed_yoe
            source_budget_yoe[yr] -= proposed_yoe
        if year_col_prefix == 'cvta_':
            df2_work.at[idx, 'CVTA_Allocated_Base'] += allocated_base
            df2_work.at[idx, 'CVTA_Allocated_YOE'] += allocated_yoe
        df2_work.at[idx, 'Remaining Cost Base'] -= allocated_base
        if allocated_base > 0:
            df2_work.at[idx, 'Comment'] += f"{source_name}: ${allocated_base:.2f}M base (${allocated_yoe:.2f}M YOE). "
        if df2_work.at[idx, 'Remaining Cost Base'] <= 0:
            df2_work.at[idx, 'Fully Funded'] = True
            df2_work.at[idx, 'Comment'] += f"Fully funded by {source_name}. "

# CVTA budget
cvta_budget_yoe = {yr: df1_clean.loc[yr, 'cvta'] * CAP_PERCENTAGE for yr in years}
allocate_funds_frontloaded(chesterfield_indices, cvta_budget_yoe, 'CVTA', year_col_prefix='cvta_')

# -------------------------------
# 4. Remove fully funded Chesterfield projects from further consideration
# -------------------------------
remaining_projects = df2_work[df2_work['Remaining Cost Base'] > 0].copy()
remaining_projects = remaining_projects.sort_values('B/C Rank').reset_index(drop=True)
print(f"Projects remaining after CVTA allocation: {len(remaining_projects)}")

# -------------------------------
# 5. STEP 2: Allocate other revenue sources (excluding cvta) to remaining projects (front-loaded)
# -------------------------------
other_sources = [col for col in df1_clean.columns if col != 'cvta']
other_budgets_yoe = {}
for source in other_sources:
    other_budgets_yoe[source] = {yr: df1_clean.loc[yr, source] * CAP_PERCENTAGE for yr in years}

for idx in remaining_projects.index:
    source = df2_work.at[idx, 'Primary Funding Source']
    if source not in other_sources:
        df2_work.at[idx, 'Comment'] += f"Source '{source}' not in available budget (excluding cvta). "
        continue
    remaining_base = df2_work.at[idx, 'Remaining Cost Base']
    if remaining_base <= 0:
        continue
    allocated_base = 0
    allocated_yoe = 0
    for yr in years:
        if remaining_base - allocated_base <= 1e-6:
            break
        annual_cap_yoe = other_budgets_yoe[source].get(yr, 0)
        if annual_cap_yoe <= 0:
            continue
        proposed_base = remaining_base - allocated_base
        proposed_yoe = calculate_yoe_cost(proposed_base, yr)
        if proposed_yoe > annual_cap_yoe:
            max_base = calculate_base_cost(annual_cap_yoe, yr)
            proposed_base = max_base
            proposed_yoe = annual_cap_yoe
        if proposed_base <= 0:
            continue
        df2_work.at[idx, yr] += proposed_yoe
        allocated_base += proposed_base
        allocated_yoe += proposed_yoe
        other_budgets_yoe[source][yr] -= proposed_yoe
    df2_work.at[idx, 'Remaining Cost Base'] -= allocated_base
    if allocated_base > 0:
        df2_work.at[idx, 'Comment'] += f"{source}: ${allocated_base:.2f}M base (${allocated_yoe:.2f}M YOE). "
    if df2_work.at[idx, 'Remaining Cost Base'] <= 0:
        df2_work.at[idx, 'Fully Funded'] = True
        df2_work.at[idx, 'Comment'] += f"Fully funded by {source}. "

# -------------------------------
# 6. BUDGET SWEEP
# -------------------------------
unfunded_projects = df2_work[df2_work['Remaining Cost Base'] > 0].sort_values('B/C Rank').index

for source in other_sources + ['cvta']:
    if source == 'cvta':
        budget_dict = cvta_budget_yoe
        year_prefix = 'cvta_'
    else:
        budget_dict = other_budgets_yoe.get(source, {})
        year_prefix = ''
    if not budget_dict:
        continue
    if all(budget_dict.get(yr, 0) == 0 for yr in years):
        continue
    for idx in unfunded_projects:
        if df2_work.at[idx, 'Remaining Cost Base'] <= 0:
            continue
        if source == 'cvta' and df2_work.at[idx, 'County'] != 'Chesterfield':
            continue
        if source != 'cvta' and df2_work.at[idx, 'Primary Funding Source'] != source:
            continue
        remaining_base = df2_work.at[idx, 'Remaining Cost Base']
        for yr in years:
            if remaining_base <= 1e-6:
                break
            if budget_dict.get(yr, 0) <= 0:
                continue
            proposed_yoe = min(budget_dict[yr], calculate_yoe_cost(remaining_base, yr))
            proposed_base = calculate_base_cost(proposed_yoe, yr)
            if proposed_base <= 0:
                continue
            if year_prefix:
                df2_work.at[idx, f'{year_prefix}{yr}'] += proposed_yoe
            else:
                df2_work.at[idx, yr] += proposed_yoe
            budget_dict[yr] -= proposed_yoe
            remaining_base -= proposed_base
            if source == 'cvta':
                df2_work.at[idx, 'CVTA_Allocated_Base'] += proposed_base
                df2_work.at[idx, 'CVTA_Allocated_YOE'] += proposed_yoe
            df2_work.at[idx, 'Remaining Cost Base'] -= proposed_base
            if df2_work.at[idx, 'Remaining Cost Base'] <= 1e-6:
                df2_work.at[idx, 'Fully Funded'] = True
                df2_work.at[idx, 'Comment'] += f"Fully funded by sweep ({source}). "
            else:
                df2_work.at[idx, 'Comment'] += f"Sweep allocated ${proposed_base:.2f}M base from {source}. "

# -------------------------------
# 7. Compute total allocated amounts (YOE and Base)
# -------------------------------
primary_yearly_sum = df2_work[years].sum(axis=1)
cvta_yearly_sum = df2_work[[f'cvta_{yr}' for yr in years]].sum(axis=1)
df2_work['Allocated Total (YOE $)'] = primary_yearly_sum + cvta_yearly_sum

df2_work['Allocated Total (Base $)'] = 0.0
for yr in years:
    factor = (1 + ESCALATION_RATE) ** (yr - BASE_YEAR)
    df2_work['Allocated Total (Base $)'] += (df2_work[yr] + df2_work[f'cvta_{yr}']) / factor

df2_work['Remaining Balance (Base $)'] = df2_work['Total Cost ($M)'] - df2_work['Allocated Total (Base $)']

# -------------------------------
# 7b. Add Anticipated Opening Year (last year with any funding)
# -------------------------------
def get_opening_year(row):
    funded_years = []
    for yr in years:
        if row[yr] > 0 or row[f'cvta_{yr}'] > 0:
            funded_years.append(yr)
    if funded_years:
        return max(funded_years)
    else:
        return None

df2_work['Anticipated Opening Year'] = df2_work.apply(get_opening_year, axis=1)

# -------------------------------
# 8. Merge back into original df2 for output
# -------------------------------
for yr in years:
    df2[f'cvta_{yr}'] = df2_work[f'cvta_{yr}'].reindex(df2.index, fill_value=0)
    df2[yr] = df2_work[yr].reindex(df2.index, fill_value=0)

df2['CVTA_Allocated_Base'] = df2_work['CVTA_Allocated_Base'].reindex(df2.index, fill_value=0)
df2['CVTA_Allocated_YOE'] = df2_work['CVTA_Allocated_YOE'].reindex(df2.index, fill_value=0)
df2['Allocated Total (YOE $)'] = df2_work['Allocated Total (YOE $)'].reindex(df2.index, fill_value=0)
df2['Allocated Total (Base $)'] = df2_work['Allocated Total (Base $)'].reindex(df2.index, fill_value=0)
df2['Remaining Balance (Base $)'] = df2_work['Remaining Balance (Base $)'].reindex(df2.index, fill_value=0)
df2['Fully Funded'] = df2_work['Fully Funded'].reindex(df2.index, fill_value=False)
df2['Comment'] = df2_work['Comment'].reindex(df2.index, fill_value="")
df2['Anticipated Opening Year'] = df2_work['Anticipated Opening Year'].reindex(df2.index, fill_value=None)

# -------------------------------
# 9. Build df3: annual programmed vs available
# -------------------------------
programmed_primary = {}
for source in other_sources:
    programmed_primary[source] = {}
    source_projects = df2_work[df2_work['Primary Funding Source'] == source]
    for yr in years:
        programmed_primary[source][yr] = source_projects[yr].sum()

programmed_cvta = {yr: df2_work[f'cvta_{yr}'].sum() for yr in years}

df3_data = []
for yr in years:
    row = {'Year': yr}
    for source in other_sources:
        original = df1_clean.loc[yr, source] if yr in df1_clean.index else 0
        yoe_90 = original * CAP_PERCENTAGE
        programmed = programmed_primary[source].get(yr, 0)
        util = (programmed / yoe_90 * 100) if yoe_90 > 0 else 0
        row[f'{source}_Original'] = original
        row[f'{source}_YOE_90%_Cap'] = yoe_90
        row[f'{source}_Programmed'] = programmed
        row[f'{source}_Utilization_%'] = util
    cvta_original = df1_clean.loc[yr, 'cvta'] if yr in df1_clean.index else 0
    cvta_yoe_90 = cvta_original * CAP_PERCENTAGE
    cvta_programmed = programmed_cvta.get(yr, 0)
    cvta_util = (cvta_programmed / cvta_yoe_90 * 100) if cvta_yoe_90 > 0 else 0
    row['cvta_Original'] = cvta_original
    row['cvta_YOE_90%_Cap'] = cvta_yoe_90
    row['cvta_Programmed'] = cvta_programmed
    row['cvta_Utilization_%'] = cvta_util
    df3_data.append(row)

total_row = {'Year': 'TOTAL'}
for source in other_sources + ['cvta']:
    original_total = df1_clean[source].sum() if source in df1_clean else 0
    yoe_90_total = original_total * CAP_PERCENTAGE
    if source == 'cvta':
        programmed_total = sum(programmed_cvta.values())
    else:
        programmed_total = sum(programmed_primary[source].values())
    util_total = (programmed_total / yoe_90_total * 100) if yoe_90_total > 0 else 0
    total_row[f'{source}_Original'] = original_total
    total_row[f'{source}_YOE_90%_Cap'] = yoe_90_total
    total_row[f'{source}_Programmed'] = programmed_total
    total_row[f'{source}_Utilization_%'] = util_total

df3 = pd.DataFrame(df3_data)
df3 = pd.concat([df3, pd.DataFrame([total_row])], ignore_index=True)

# -------------------------------
# 10. Output final utilization summary
# -------------------------------
print("\n")
print("=" * 80)
print("FINAL UTILIZATION BY REVENUE SOURCE (90% Cap)")
print("=" * 80)
print(df3[df3['Year'] == 'TOTAL'].T)
print("\n")

print("=" * 80)
print("ALLOCATION SUMMARY")
print("=" * 80)
print(f"Total projects funded (fully or partially): {df2[df2['Allocated Total (YOE $)'] > 0].shape[0]}")
print(f"Fully funded projects: {df2[df2['Fully Funded'] == True].shape[0]}")
print(f"Chesterfield projects fully funded by CVTA: {(df2[(df2['County'] == 'Chesterfield') & (df2['Fully Funded'] == True) & (df2['CVTA_Allocated_Base'] > 0)].shape[0])}")

# Show top 10 funded projects
print("\nTop 10 projects by B/C Rank (funded status):")
top10 = df2.nsmallest(10, 'B/C Rank')[['Project ID', 'Project Name', 'County', 'Total Cost ($M)', 'Allocated Total (YOE $)', 'Fully Funded', 'Anticipated Opening Year']]
print(top10.to_string(index=False))

# -------------------------------
# 11. Export to CSV
# -------------------------------
df2.to_csv('df2_allocated_cvta_priority.csv', index=False)
df3.to_csv('df3_budget_comparison_cvta.csv', index=False)

print("\n")
print("=" * 80)
print("EXPORT COMPLETE")
print("=" * 80)
print("✓ df2_allocated_cvta_priority.csv")
print("  - Includes 'Anticipated Opening Year' = last year with any funding")
print("  - CVTA funds used only for Chesterfield projects (sorted by B/C Rank)")
print("  - Front-loaded allocation: each project funded in earliest possible years, minimizing gaps")
print("  - Fully funded Chesterfield projects are removed from step 2")
print("  - Other revenue sources fund remaining projects")
print("  - Budget sweep ensures near-100% utilization of the 90% cap")
print("\n✓ df3_budget_comparison_cvta.csv")
print("  - Shows annual original, 90% cap, programmed, and utilization for all sources (including cvta)")











